services:
  db:
    image: mysql:8.0.35
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  web:
    build:
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    restart: always # コンテナが停止すると常に再起動
    stdin_open: true
    tty: true
  solid_que_worker:
    build:
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
    command: bash -c "bin/jobs"
    volumes:
      - .:/app
volumes:
  mysql_volume:
    driver: local
